# Generated by Django 4.2.5 on 2023-10-28 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('mobile', models.PositiveIntegerField()),
                ('adress', models.TextField()),
                ('password', models.CharField(max_length=50)),
                ('profile_pic', models.ImageField(default='', upload_to='profile_pic/')),
                ('usertype', models.CharField(default='buyer', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_categories', models.CharField(choices=[('Shirt', 'Shirt'), ('Pant', 'Pant'), ('Shoes', 'Shoes')], max_length=60)),
                ('product_name', models.CharField(max_length=100)),
                ('product_brand', models.CharField(max_length=60)),
                ('product_size', models.CharField(max_length=60)),
                ('product_price', models.PositiveIntegerField()),
                ('product_pic', models.ImageField(upload_to='product_pic/')),
                ('product_information', models.TextField()),
                ('product_description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
