from django.urls import path
from . import views

urlpatterns = [
    path('',views.index,name='index'),
    path('blog-details/',views.blog_details,name='blog-details'),
    path('blog/',views.blog,name='blog'),
    path('checkout/',views.checkout,name='checkout'),
    path('contact/',views.contact,name='contact'),
    path('main/',views.main,name='main'),
    path('shop/',views.shop,name='shop'),
    path('shop-all/',views.shop,name='shop-all'),
    path('shop-shirt/',views.shop_shirt,name='shop-shirt'),
    path('shop-pant/',views.shop_pant,name='shop-pant'),
    path('shop-shoes/',views.shop_shoes,name='shop-shoes'),
    path('shopping-cart/',views.shopping_cart,name='shopping-cart'),
    path('about/',views.about,name='about'),
    path('signup/',views.signup,name='signup'),
    path('login/',views.login,name='login'),
    path('logout/',views.logout,name='logout'),
    path('change-password/',views.change_password,name='change-password'),
    path('forgot-password/',views.forgot_password,name='forgot-password'),
    path('verify-otp/',views.verify_otp,name='verify-otp'),
    path('new-password/',views.new_password,name='new-password'),
    path('seller-add-product/',views.seller_add_product,name='seller-add-product'),
    path('seller-index',views.index,name='seller-index'),
    path('seller-view-product',views.seller_view_product,name='seller-view-product'),
    path('seller-view-product-shirt/',views.seller_view_product_shirt,name='seller-view-product-shirt'),
    path('seller-view-product-pant/',views.seller_view_product_pant,name='seller-view-product-pant'),
    path('seller-view-product-shoes/',views.seller_view_product_shoes,name='seller-view-product-shoes'),
    path('seller-view-product-all/',views.seller_view_product_all,name='seller-view-product-all'),
    path('seller-view-product-details/<int:pk>/',views.seller_view_product_details,name='seller-view-product-details'),
    path('seller-product-edit/<int:pk>/',views.seller_product_edit,name='seller-product-edit'),
    path('seller-product-delete/<int:pk>/',views.seller_product_delete,name='seller-product-delete'),
    path('single-product/<int:pk>/',views.single_product,name='single-product'),
    path('add-to-wishlist/<int:pk>/',views.add_to_wishlist,name='add-to-wishlist'),
    path('wishlist/',views.wishlist,name='wishlist'),
    path('remove-from-wishlist/<int:pk>/',views.remove_from_wishlist,name='remove-from-wishlist'),
    path('add-to-cart/<int:pk>',views.add_to_cart,name='add-to-cart'),
    path('remove-from-cart/<int:pk>/',views.remove_from_cart,name='remove-from-cart'),
    path('change-quantity/',views.change_quantity,name='change-quantity'),
    path('create-checkout-session/', views.create_checkout_session, name='payment'),
    path('success.html/', views.success,name='success'),
    path('cancel.html/', views.cancel,name='cancel'),
    path('myorder/',views.myorder,name='myorder'),
    path('seller-order/',views.seller_order,name='seller-order'),
    path('ajax/validate_email/',views.validate_signup,name='validate_email'),
]